version: '3.7'
services:
  mqtt:
    image: eclipse-mosquitto
    restart: always
    network_mode: "host"
    volumes:
      - /srv/mqtt:/mosquitto
  hass:
    image: homeassistant/home-assistant
    init: true
    restart: always
    network_mode: "host"
    environment:
      - "TZ=America/Denver"
    volumes:
      - /srv/hass:/config
