---

- name: "Download Mosquitto Image"
  docker_image:
    name: eclipse-mosquitto
    source: pull

- name: "Copy Mosquitto.conf"
  copy:
    src: files/mosquitto.conf
    dest: /srv/mqtt/config/

- name: "Create empty password file"
  file:
    state: touch
    path: /srv/mqtt/pwfile

- name: "Create CA Private Key"
  openssl_privatekey:
    path: /srv/mqtt/config/ca.key
    size: 2048

- name: "Create Certificate"
  shell:
    cmd: "openssl req -new -key ca.key -x509 -days 365 -out ca.crt -subj '/C={{ country_name }}/ST={{ state_name }}/L={{ city_name }}/O={{ org_name }}/OU={{ org_unit_name }}/CN={{ cn }}-ca'"
    chdir: /srv/mqtt/config/

- name: "Create Server Key"
  openssl_privatekey:
    path: /srv/mqtt/config/server.key
    size: 2048

- name: Generate an OpenSSL Certificate Signing Request with Subject information
  openssl_csr:
    path: /srv/mqtt/config/server.csr
    privatekey_path: /srv/mqtt/config/server.key
    country_name: "{{ country_name }}"
    organization_name: "{{ org_name }}"
    common_name: "{{ cn }}"

- name: "Sign CSR"
  shell:
    cmd: openssl x509 -req -in server.csr -CA ca.crt -CAkey ca.key -CAcreateserial -out server.crt
    chdir: /srv/mqtt/config

- name: Generate an OpenSSL certificate signed with your own CA certificate
  openssl_certificate:
    path: /srv/mqtt/config/server.crt
    csr_path: /srv/mqtt/config/server.csr
    ownca_path: /srv/mqtt/config/ca.crt
    ownca_privatekey_path: /srv/mqtt/config/ca.key
    provider: ownca
  